# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
    ./docker/scripts/dev_start.sh -t dev-x86_64-20180806_1111
  displayName: 'Initialize'
- script: 
    echo CI Lint
    ./apollo-docker.sh lint
  displayName: 'Lint'
